### ISSUE TITLE
Usage example not working

### ISSUE THREAD

**Issue by agregory65** [mullenkamp/nasadap#1]
Hello,

I have tried running the usage example and get an error as shown below. I have installed all of the dependencies, so I'm not sure if it's something on my side or something else. Can you help with this issue please?

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-274a478e760c> in <module>()
     23 ### Examples
     24 
---> 25 min_max = min_max_dates(mission1) # Will give you the min and max available dates for products
     26 

~/anaconda3/lib/python3.6/site-packages/nasadap/util.py in min_max_dates(missions, products)
    105             dataset = et.getchildren()[2].getchildren()
    106 
--> 107             min_attrib = dataset[0].attrib
    108             min_year = min_attrib['name']
    109 

IndexError: list index out of range

**Comment by mullenkamp** [comment]
Thanks for that. It looks like it's been broken for some months now and I just hadn't checked the process in a while. 
I'm making some updates that will fix this and hopefully make it a bit more flexible. The version 6 is now out, so I definitely want to include this now.

**Comment by mullenkamp** [comment]
Should be fixed now #2 #3 
Let me know if you still have issues.
